#!/usr/bin/with-contenv bash

# used https://github.com/linuxserver/docker-plex as a template

POPULATE_EXAMPLES=false

echo "-------------------------------------"
echo -e "Setting up app config directory based on CONFIG_DIR env: ${CONFIG_DIR}\n"

# make config folder if it does not exist
if [ ! -d "${CONFIG_DIR}" ]; then
  echo "Directory does not exist! Creating..."
  POPULATE_EXAMPLES=true
  mkdir -p "${CONFIG_DIR}"
else
  if [ "$(ls -A ${CONFIG_DIR})" ]; then
       echo "Directory is not empty, not populating with defaults."
    else
      POPULATE_EXAMPLES=true
    fi
fi

# add example configs
if [ "$POPULATE_EXAMPLES" = true ]; then
  echo "Directory is empty, adding defaults..."
  mkdir -p "${CONFIG_DIR}"/static
  cp -r /app/static/. "${CONFIG_DIR}"/static
  mv /app/config/monitors.example.yaml "${CONFIG_DIR}"/monitors.yaml
  mv /app/config/site.example.yaml "${CONFIG_DIR}"/site.yaml
fi

# permissions
echo "chown'ing directory to ensure correct permissions."
chown -R abc:abc "${CONFIG_DIR}"
echo "Done!"
echo -e "-------------------------------------\n"
