apiVersion: surface/v1
kind: API
tests:
  - name: home-page
    method: GET
    path: /
    expect:
      status: 200

  - name: openapi-spec
    method: GET
    path: /docs/spec/v4/spec.json
    expect:
      status: 200
      equal:
        body.openapi: "3.1.0"

  - name: api-needs-a-key
    method: GET
    path: /api/v4/monitors
    expect:
      status: 401
      body: {"error": {"code": "UNAUTHORIZED"}}
